---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: 390102656945.dkr.ecr.us-west-2.amazonaws.com/cicdpipelineapp:latest
        ports:
        - containerPort: 80
